USE [master]
GO
/****** Object:  Database [RepairRequestsDB]    Script Date: 22.11.2024 19:46:04 ******/
CREATE DATABASE [RepairRequestsDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RepairRequestsDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\RepairRequestsDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'RepairRequestsDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\RepairRequestsDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [RepairRequestsDB] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RepairRequestsDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [RepairRequestsDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [RepairRequestsDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [RepairRequestsDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [RepairRequestsDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [RepairRequestsDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [RepairRequestsDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [RepairRequestsDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [RepairRequestsDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [RepairRequestsDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [RepairRequestsDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [RepairRequestsDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [RepairRequestsDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [RepairRequestsDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [RepairRequestsDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [RepairRequestsDB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [RepairRequestsDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [RepairRequestsDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [RepairRequestsDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [RepairRequestsDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [RepairRequestsDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [RepairRequestsDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [RepairRequestsDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [RepairRequestsDB] SET RECOVERY FULL 
GO
ALTER DATABASE [RepairRequestsDB] SET  MULTI_USER 
GO
ALTER DATABASE [RepairRequestsDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [RepairRequestsDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [RepairRequestsDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [RepairRequestsDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [RepairRequestsDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [RepairRequestsDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'RepairRequestsDB', N'ON'
GO
ALTER DATABASE [RepairRequestsDB] SET QUERY_STORE = ON
GO
ALTER DATABASE [RepairRequestsDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [RepairRequestsDB]
GO
/****** Object:  Table [dbo].[RepairRequests]    Script Date: 22.11.2024 19:46:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RepairRequests](
	[RequestID] [int] IDENTITY(1,1) NOT NULL,
	[RequestDate] [datetime] NOT NULL,
	[EquipmentName] [nvarchar](255) NOT NULL,
	[FaultType] [nvarchar](255) NOT NULL,
	[Description] [nvarchar](max) NOT NULL,
	[ClientName] [nvarchar](255) NOT NULL,
	[Status] [nvarchar](50) NOT NULL,
	[AssignedEmployee] [nvarchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[RequestID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  View [dbo].[RepairStatistics]    Script Date: 22.11.2024 19:46:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- Создание представления для статистики
CREATE VIEW [dbo].[RepairStatistics] AS
SELECT
    COUNT(RequestID) AS TotalRequests,          -- Общее количество заявок
    SUM(CASE WHEN Status = 'Выполнено' THEN 1 ELSE 0 END) AS CompletedRequests, -- Выполненные заявки
    AVG(DATEDIFF(HOUR, RequestDate, GETDATE())) AS AvgCompletionTime -- Среднее время выполнения (в часах)
FROM RepairRequests;

GO
/****** Object:  Table [dbo].[Employees]    Script Date: 22.11.2024 19:46:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Employees](
	[EmployeeID] [int] IDENTITY(1,1) NOT NULL,
	[EmployeeName] [nvarchar](255) NOT NULL,
	[Position] [nvarchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[EmployeeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RequestComments]    Script Date: 22.11.2024 19:46:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RequestComments](
	[CommentID] [int] IDENTITY(1,1) NOT NULL,
	[RequestID] [int] NOT NULL,
	[EmployeeID] [int] NOT NULL,
	[CommentText] [nvarchar](max) NOT NULL,
	[CommentDate] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CommentID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[RequestComments] ADD  DEFAULT (getdate()) FOR [CommentDate]
GO
ALTER TABLE [dbo].[RequestComments]  WITH CHECK ADD FOREIGN KEY([EmployeeID])
REFERENCES [dbo].[Employees] ([EmployeeID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[RequestComments]  WITH CHECK ADD FOREIGN KEY([RequestID])
REFERENCES [dbo].[RepairRequests] ([RequestID])
ON DELETE CASCADE
GO
USE [master]
GO
ALTER DATABASE [RepairRequestsDB] SET  READ_WRITE 
GO
